//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bazdanEntities : DbContext
    {
        public bazdanEntities()
            : base("name=bazdanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Администратор> Администратор { get; set; }
        public virtual DbSet<Биоматериалы> Биоматериалы { get; set; }
        public virtual DbSet<Данные_пациентов> Данные_пациентов { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<История> История { get; set; }
        public virtual DbSet<Приборы> Приборы { get; set; }
        public virtual DbSet<Работа_анализатора> Работа_анализатора { get; set; }
        public virtual DbSet<Роль_пользователя> Роль_пользователя { get; set; }
        public virtual DbSet<Состояние_услуги> Состояние_услуги { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Статус_Заказа> Статус_Заказа { get; set; }
        public virtual DbSet<Статус_Услуги> Статус_Услуги { get; set; }
        public virtual DbSet<Страховые_компании> Страховые_компании { get; set; }
        public virtual DbSet<Тип_полиса> Тип_полиса { get; set; }
        public virtual DbSet<Услуги_Пользователя> Услуги_Пользователя { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
    }
}
