//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Данные_пациентов
    {
        public int Код_пациента { get; set; }
        public string ФИО_пациента { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Серия_паспорта { get; set; }
        public string Номер_паспорта { get; set; }
        public string Номер_телефона { get; set; }
        public string Номер_полиса { get; set; }
        public Nullable<int> Тип_полиса { get; set; }
        public Nullable<int> Страховая_компания { get; set; }
        public string Электронная_почта { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        public virtual Тип_полиса Тип_полиса1 { get; set; }
        public virtual Страховые_компании Страховые_компании { get; set; }
    }
}
