//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Состояние_услуги = new HashSet<Состояние_услуги>();
        }
    
        public int Код_заказа { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<int> Статус_заказа { get; set; }
        public string Время_выполнения_заказа { get; set; }
        public Nullable<int> Код_биоматериала { get; set; }
        public Nullable<int> Код_пациента { get; set; }
        public string result { get; set; }
    
        public virtual Биоматериалы Биоматериалы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состояние_услуги> Состояние_услуги { get; set; }
        public virtual Статус_Заказа Статус_Заказа1 { get; set; }
    }
}
