//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Услуги_Пользователя = new HashSet<Услуги_Пользователя>();
        }
    
        public int Код_сотрудника { get; set; }
        public string ФИО_сотрудника { get; set; }
        public string Email { get; set; }
        public string Номер { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> Последний_вход { get; set; }
        public Nullable<int> Услуги_сотрудника { get; set; }
        public Nullable<int> Роль_сотрудника { get; set; }
        public string Вход { get; set; }
    
        public virtual Роль_пользователя Роль_пользователя { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Услуги_Пользователя> Услуги_Пользователя { get; set; }
    }
}
