//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Страховые_компании
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Страховые_компании()
        {
            this.Данные_пациентов = new HashSet<Данные_пациентов>();
        }
    
        public int Код_компании { get; set; }
        public string Название_компании { get; set; }
        public string Адрес { get; set; }
        public string ИНН { get; set; }
        public string Расчетный_счет { get; set; }
        public string БИК { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Данные_пациентов> Данные_пациентов { get; set; }
    }
}
