//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Услуги()
        {
            this.Состояние_услуги = new HashSet<Состояние_услуги>();
            this.Услуги_Пользователя = new HashSet<Услуги_Пользователя>();
        }
    
        public int Код_услуги { get; set; }
        public Nullable<int> Номер_услуги { get; set; }
        public string Наименование_услуги { get; set; }
        public Nullable<decimal> Стоимость_услуги { get; set; }
        public Nullable<int> Время_выполнения { get; set; }
        public Nullable<int> Среднее_отклонение { get; set; }
        public Nullable<int> Анализатор { get; set; }
        public string result { get; set; }
    
        public virtual Приборы Приборы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состояние_услуги> Состояние_услуги { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Услуги_Пользователя> Услуги_Пользователя { get; set; }
    }
}
